- name: Configure Docker and deploy app on EC2
  hosts: all
  become: true
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Deploy Docker container
      docker_container:
        name: insure-me
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        published_ports:
          - "8084:8081"
